id = "pony"
name = "Pony"
description = "Pony language support with syntax highlighting"
version = "0.1.0"
schema_version = 1
authors = ["Orien Madgwick <497874+orien@users.noreply.github.com>"]
repository = "https://github.com/orien/pony-zed-extension"

[grammars.pony]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-pony"
commit = "73ff874ae4c9e9b45462673cbc0a1e350e2522a7"
